#base image
FROM node:20-alpine

#working directory
WORKDIR /src

#copy files
COPY package*.json ./
ARG NODE_ENV
RUN if ["${NODE_ENV}" = "production"]; \
    then npm install --only=production; \
    else npm install; \
    fi
    
COPY . .

#expose port
EXPOSE 3000

#run app
# CMD ["npm", "start"]
# CMD ["npm", "run", "start-dev"]
