FROM node:20-alpine
WORKDIR /src
COPY package*.json ./
ARG NODE_ENV
RUN if ["${NODE_ENV}" = "production"]; \
    then npm install --only=production; \
    else npm install; \
    fi
COPY . .
COPY ./common /common
EXPOSE 3000

