services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
      args:
        - NODE_ENV=development
      target: dev
    volumes:
      - ./apps/auth-service:/app
      - /app/node_modules
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    env_file:
      - ./apps/auth-service/.env
    ports:
      - '3000:3000'
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - redis
    networks:
      - mongo-network
    command: dev
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/v1/health-check']
      interval: 10s
      timeout: 10s
      start_period: 20s
      retries: 5

  car-service:
    container_name: car-service
    build:
      context: .
      dockerfile: apps/car-service/Dockerfile
      args:
        - NODE_ENV=development
      target: dev
    volumes:
      - ./apps/car-service:/app
      - /app/node_modules
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    env_file:
      - ./apps/car-service/.env
    ports:
      - '4000:4000'
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - kafka
      - zookeeper
    networks:
      - mongo-network
      - kafka-network
    command: dev
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/api/v1/health-check']
      interval: 10s
      timeout: 10s
      start_period: 20s
      retries: 5

  elastic-service:
    container_name: elastic-service
    build:
      context: .
      dockerfile: apps/elastic-service/Dockerfile
      args:
        - NODE_ENV=development
      target: dev
    volumes:
      - ./apps/elastic-service:/app
      - /app/node_modules
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    env_file:
      - ./apps/elastic-service/.env
    ports:
      - '5000:5000'
    depends_on:
      - elasticsearch
      - kafka
      - zookeeper
    networks:
      - mongo-network
      - kafka-network
    command: dev
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/api/v1/health-check']
      interval: 10s
      timeout: 10s
      start_period: 20s
      retries: 5

  # payment-service:
  #   container_name: payment-service
  #   build:
  #     context: ./payment-service
  #     args:
  #       - NODE_ENV=development
  #   volumes:
  #     - ./payment-service:/app
  #   env_file:
  #     - ./payment-service/.env
  #   ports:
  #     - '6000:6000'
  #   depends_on:
  #     - kafka
  #     - zookeeper
  #   networks:
  #     - mongo-network
  #     - kafka-network
