name: Deploy to Docker Hub and EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run Prettier and ESLint
        run: npm ci
          npm run lint
          npm run format

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Images
        run:
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest ./auth-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/car-service:latest ./car-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/elastic-service:latest ./elastic-service

      - name: Push Docker Images
        run: docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/car-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/elastic-service:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: docker pull ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/car-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/elastic-service:latest

            docker stop auth-service || true && docker rm auth-service || true
            docker stop car-service || true && docker rm car-service || true
            docker stop elastic-service || true && docker rm elastic-service || true

            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
