# ===== Build Stage =====
FROM node:20-alpine AS  builder
WORKDIR /src
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# ===== Development Stage =====
FROM node:20 AS  dev
WORKDIR /src
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 4000
RUN chmod +x docker-entrypoint.sh
ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["dev"]

# ===== Production Stage =====
FROM node:20-alpine AS  prod
WORKDIR /src
RUN npm install -g pm2
COPY package*.json ./
RUN npm install --only=production
COPY --from=builder /src/dist ./dist
COPY --from=builder /src/ecosystem.config.js ./ecosystem.config.js
COPY --from=builder /src/docker-entrypoint.sh ./docker-entrypoint.sh
EXPOSE 4000
RUN chmod +x docker-entrypoint.sh
ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["pm2"]
