version: "3.8"
services:
  auth-service:
    build:
      context: ./auth-service
      args:
        - NODE_ENV=development
    command: sh -c "sleep 10 && npm run start-dev"

  car-service:
    build:
      context: ./car-service
      args:
        - NODE_ENV=development
    command: sh -c "sleep 10 && npm run start-dev"
<<<<<<< Updated upstream
=======

  elastic-service:
    build:
      context: ./elastic-service
      args:
        - NODE_ENV=development
    command: sh -c "sleep 10 && npm run start-dev"
>>>>>>> Stashed changes
