services:
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      args:
        - NODE_ENV=development
    volumes:
      - ./auth-service:/src
    env_file:
      - ./auth-service/.env
    ports:
      - '3000:3000'
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - redis
    networks:
      - mongo-network
    # command: sh -c "sleep 10 && npm run dev"
    command: ["dev"]

  car-service:
    container_name: car-service
    build:
      context: ./car-service
      args:
        - NODE_ENV=development
    volumes:
      - ./car-service:/src
    env_file:
      - ./car-service/.env
    ports:
      - '4000:4000'
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - kafka
      - zookeeper
    networks:
      - mongo-network
      - kafka-network
    # command: sh -c "sleep 10 && npm run dev"
    command: ["dev"]

  elastic-service:
    container_name: elastic-service
    build:
      context: ./elastic-service
      args:
        - NODE_ENV=development
    volumes:
      - ./elastic-service:/src
    env_file:
      - ./elastic-service/.env
    ports:
      - '5000:5000'
    depends_on:
      - elasticsearch
      - kafka
      - zookeeper
    networks:
      - mongo-network
      - kafka-network
    # command: sh -c "sleep 10 && npm run dev"
    command: ["dev"]

  payment-service:
    container_name: payment-service
    build:
      context: ./payment-service
      args:
        - NODE_ENV=development
    volumes:
      - ./payment-service:/src
    env_file:
      - ./payment-service/.env
    ports:
      - '6000:6000'
    depends_on:
      - kafka
      - zookeeper
    networks:
      - mongo-network
      - kafka-network
    # command: sh -c "sleep 10 && npm run dev"
    command: ["dev"]
