services:
  auth-service:
    image: amrgamaleid/auth-service
    build:
      context: ./auth-service
      args:
        - NODE_ENV=production
    command: sh -c "sleep 20 && npm run start"

  car-service:
    image: amrgamaleid/car-service
    build:
      context: ./car-service
      args:
        - NODE_ENV=production
    command: sh -c "sleep 20 && npm run start"
