services:
  auth-service:
    image: amrgamaleid/auth-service
    build:
      context: ./auth-service
      args:
        - NODE_ENV=production
    command: ['pm2'] # Defualt pm2

  car-service:
    image: amrgamaleid/car-service
    build:
      context: ./car-service
      args:
        - NODE_ENV=production
    command: ['pm2']

  elastic-service:
    image: amrgamaleid/elastic-service
    build:
      context: ./elastic-service
      args:
        - NODE_ENV=production
    command: ['pm2']

  payment-service:
    image: amrgamaleid/payment-service
    build:
      context: ./payment-service
      args:
        - NODE_ENV=production
    command: ['pm2']
