name: CI/CD Pipeline

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main]

jobs:
  check-code:
    name: Check Lint and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run ESLint & Prettier
        run: |
          npm run lint
          npm run format

  deploy:
    name: Deploy to EC2 (Only on main)
    runs-on: ubuntu-latest
    needs: check-code
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run ESLint & Prettier
        run: |
          npm run lint
          npm run format

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Images with buildx
        run: |
            docker-compose -f server/docker-compose.yml -f server/docker-compose.prod.yml build

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/car-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/elastic-service:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/car-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/elastic-service:latest

            docker stop auth-service || true && docker rm auth-service || true
            docker stop car-service || true && docker rm car-service || true
            docker stop elastic-service || true && docker rm elastic-service || true

            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
